### ISSUE TITLE
Is the signalk-server-windows usable with N2k?

### ISSUE THREAD

**Issue by hreuver0183** [SignalK/signalk-server-windows#11]
For a Windows user I'm looking for advise on whether he should install the windows server or whether to add an RPI to his network. Basic functionality should include a connection to an NMEA2000 network. I haven't found any information on that for the windows server.

Basically:
- What N2k connections are advised? The Actisense NGT-1? The Canable (Pro)?
- What software do I need between the SignalK server and the USB port? Or is the driver included with SignalK?

**Comment by tkurki** [comment]
I would think USB based products like NGT-1 and https://digitalyachtamerica.com/product/ikonvert-usb/ would work out of the box. Something that is pretty failsafe / future proof is a network-based gateway  like https://www.yachtd.com/products/wifi_gateway.html or https://www.yachtd.com/products/ethernet_gateway.html - they need only networking, so not dependent on any Windows hardware compatibility.

But I have not personally used SK on windows. What you could do is ask for people who have experience with this at 
- https://signalk-dev.slack.com/  (http://slack-invite.signalk.org/)
- OpenPlotter forum https://forum.openmarine.net/forumdisplay.php?fid=1
- Cruisers' Forum https://www.cruisersforum.com/

**Comment by hreuver0183** [comment]
Ah, the quick solution would then be either a Yacht Devices gateway or an RPI with SignalK I guess.
