### ISSUE TITLE
How to configure SignalK to get Nmea2K data from the waveshare USB-CAN-A 

### ISSUE THREAD

**Issue by andreshs1** [SignalK/signalk-server-windows#17]
Hi there 

I am running signalK on windows and I am connected to the N2K bus with a Waveshare USB-CAN-A. I have tested the connection and I can see Nmea2K data. But I am not able to configure it as a data source on SignalK

any ideas/help?

thanks in advance

**Comment by cmotelet** [comment]
Hi,
Select data type: NMEA2000
And try in the “NMEA 2000 Source” list an entry that displays “Serial port”.
I'm currently on the boat and have little means of searching, so I don't know whether the “USB-CAN-A” converter is supported by the canboat or canboatjs decoder.
Supported hardware is listed here: https://github.com/SignalK/signalk-server/wiki/FAQ:-Frequently-Asked-Questions#how-do-i-integrate-with-nmea2000-can-bus.

@tkurki or @sbender9 , do you have an opinion on the support for this type of converter ?
https://www.waveshare.com/wiki/USB-CAN-A

You'll find more support on discord : https://discord.gg/uuZrwz4dCS

**Comment by sbender9** [comment]
This device is not currently supported. No plans to add it at this time.

**Comment by andreshs1** [comment]
Hi both

Thank you for the reply

That is a real shame, as it is a great (affordable ) solution, and works great on Home Assistant 

Cheers

**Comment by sbender9** [comment]
There just hasn't been any demand, In all these years you're the first to ask for it.

**Comment by andreshs1** [comment]
Hi,  understood 
I was just keen of getting the nmea data into signalk for less than 10USD

Regards
Andres

**Comment by spidgrou** [comment]
I am actually using the same adapter (Waveshare USB-CAN-A) on our boat and ran into the same wall. Ended up writing a small Python bridge that reads the N2K frames from the serial port (CH340) and forwards them to a virtual CAN interface (vcan0). From there SignalK picks them up normally through its existing canbus-canboatjs provider. Its been running for a few days and seems to work fine.

Sharing in case someone else ends up here looking for a solution:
https://github.com/spidgrou/nmea2000-can-bridge

Not a polished product by any means, but it does the job.
