### ISSUE TITLE
Installation refuses on a Win10

### ISSUE THREAD

**Issue by ghost** [SignalK/signalk-server-windows#2]
Hi, thanks for this great initiative, particularly getting SK running as a service would be great! Unfortunately, for me the installation does not fly:
![Annotation 2020-05-02 102049](https://user-images.githubusercontent.com/6381128/80859321-20026b80-8c60-11ea-881f-daa951233b8f.jpg)
My machine details are in this zipped text file: 
[Annotation 2020-05-02 102049.zip](https://github.com/SignalK/signalk-server-windows/files/4567322/Annotation.2020-05-02.102049.zip)

**Comment by ghost** [comment]
FYI, I forked your project, fetched its NSIS locally on the above computer and built the *.exe. Now it launches and installs. Maybe the *.exe you are pointing to in 'master' branch is not up to date with your NSIS config in the repo? If you have a new *.exe to test, let me know. Meanwhile, please find my findings in the attached zip file. Great job! Definitely a game changer for those Windows users interested in Signal K but not RPI and Node.js. I hope... 😀 
[Annotation 2020-05-02 102049_test_NSIS-build.zip](https://github.com/SignalK/signalk-server-windows/files/4567482/Annotation.2020-05-02.102049_test_NSIS-build.zip)

**Comment by cmotelet** [comment]
Many thanks for these very interesting logs.
I fixed the problem with the service installation with the new installer 0.3.1 version.

**Comment by cmotelet** [comment]
I still have no idea about the problem of executing the exe from github with your PC.
I checked and it was the same as the one at my local repo place.
Double check if your anti-virus did not block it.

**Comment by cmotelet** [comment]
In `signalk-cli`, about `signalk-server` vs `signalk-server.cmd`,
There is 3 files in `nodejs` dir:
- signalk-server
- signalk-server.cmd
- signalk-server.ps1

By running `signalk-server` the system may choose one of those.
If you run `signalk-server.cmd`, you are sure to use the correct file. But it's true `signalk-server` also works.

**Comment by cmotelet** [comment]
In your screenshot, there is no icon on the exe file, may be a clue...
![image](https://user-images.githubusercontent.com/31212553/80864868-e04e7a80-8c85-11ea-8731-de1bde5f1c92.png)

**Comment by ghost** [comment]
Yes, I think you can close your first ticket in this project... 👍
I downloaded the *exe from your repo fresh 29 minutes ago [https://github.com/SignalK/signalk-server-windows/blob/de33213c51f84de317d650018d31565af45e779f/output/signalk-server-setup.exe](here) and it is considerably larger than the one I downloaded the 29th of April...:

![Annotation 2020-05-02 150155](https://user-images.githubusercontent.com/6381128/80864960-72568300-8c86-11ea-9c08-8a2d30011410.jpg)
 
This explains that.... Here's the NSIS output now:
[Annotation 2020-05-02 145600_test_exe_NSIS-log.zip](https://github.com/SignalK/signalk-server-windows/files/4567743/Annotation.2020-05-02.145600_test_exe_NSIS-log.zip)

Also, now the launch as Service now works:
![Annotation 2020-05-02 145957](https://user-images.githubusercontent.com/6381128/80865003-b5185b00-8c86-11ea-816d-7626bc744705.jpg)

I'll start using now this service based server as my primary test bed with Signal K and will come back in other tickets if a need arise.

P.S. IMO it would be better off if you would start using GitHub's Release feature instead of git syncing your executable in the /output folder, put the folder in your `.gitignore` and instead, when you are ready to release, upload the result from your own computer into to the Release note's attachements. This way, there would be no ambiguity which version your peers are using - especially if you put the version in the file name. That's my two cents worth to your great project, thanks!

**Comment by cmotelet** [comment]
- GitHub's Release v0.3.1 done
- readme updated to direct download:
 https://github.com/SignalK/signalk-server-windows/releases/latest/download/signalk-server-setup.exe

I chose not to put the version in the filename to have a fixed link in the readme.
The version can be found when you run it without installing anything.
