### ISSUE TITLE
error with installer 3.0.1

### ISSUE THREAD

**Issue by tonipezzoni** [SignalK/signalk-server-windows#4]
Hello,
using several pcs, from some days it's impossible to install, the error is in the picture.
Any news?
thank you

![nodejsfail](https://user-images.githubusercontent.com/67789999/86471979-aa3d7d80-bd3e-11ea-9e5b-93a931942c13.png)

**Comment by cmotelet** [comment]
@tonipezzoni ,
The installer kit downloads nodejs in HTTP and the nodejs.org web site has setup a redirect to HTTPS that does not followed by the installer.
I will build a new release tomorrow to download directly in HTTPS.
I send you a message when everything is OK.

**Comment by cmotelet** [comment]
@tonipezzoni ,
new release 0.3.2 with https fix: https://github.com/SignalK/signalk-server-windows/releases/latest/download/signalk-server-setup.exe
Can you test, comments are welcome.

**Comment by cmotelet** [comment]
closed by #5
