### ISSUE TITLE
signalk-server-windows fails to install on win10

### ISSUE THREAD

**Issue by virtuvas** [SignalK/signalk-server-windows#8]
good evening,

tried on two PCs both with win10 latest ver/updates. Both failed the same way with same error. Attaching the install.log file

[install.log](https://github.com/SignalK/signalk-server-windows/files/5961520/install.log)

you'll notice that it fails in unziping nodejs.zip which is expected as the file saved in the signalk dir is named node-v10.23.0-win-x64.zip!
just in case, I renamed this leftover file after a failed install attempt to nodejs.zip, and next attempt at installing worked!
so just a note in case it's some sort of new quirk of windows that does this.

thanks

Vassilis

**Comment by cmotelet** [comment]
Thanks for opening this issue.
I will try to reproduce tonight.
My first idea without any testing would be that the anti-virus is still analyzing the zip (and lock it) while the installer is trying to decompress it.
Your drive V:\ is a network drive or a local drive ?

**Comment by virtuvas** [comment]
A/V (MS defender, was disabled) and no other A/V active.
V is my second physical drive (got C SSD for system, rest going to an old school drive)
Tried C as well just in case, same thing.
Made sure I've edited folder permissions to give full access to everybody just in case, although I'm admin and run the setup as admin as well (right click on file name)
So I assume I got that covered.

Interesting is that when installation process dies, I'm left with the node-v10.23.0-win-x64.zip plus the log. It's not deleted. Seems like system doesn't know that this file is there as it assumed that the wget will bring and name the file as nodejs.zip.

btw, you wouldn't happen to have any idea on how to connect from signalk to the venus VRM site and get their data into another local DB? That's where I'm stuck now that I managed to install signalk!

cheers

V.

**Comment by cmotelet** [comment]
I don't understand where your `node-v10.23.0-win-x64.zip` file comes from. The installer downloads nodejs as `nodejs.zip`.
I have just rechecked by doing an installation on a W10 with the latest updates on which SignalK had never been installed.
I even checked with procmon and it is indeed the file `nodejs.zip` which is written on the disk.
![signalk-wget](https://user-images.githubusercontent.com/31212553/107740575-c14c4100-6d0b-11eb-8d17-3c434931664e.png)

**Comment by cmotelet** [comment]
For your question about `venus VRM site`, please join us on slack to ask this question.
http://slack-invite.signalk.org/ in channel #support

**Comment by virtuvas** [comment]
![signalk_install_problem](https://user-images.githubusercontent.com/17377407/107743955-830a4e00-6d1a-11eb-8bfe-2f283d242238.jpg)

just now mine. Honestly have no idea, note the ftp failure at the top, I guess it is irrelevant? your wget window doesn't seem to show that communication for some reason, only the https one.

Wonder why mine doesn't even mention the full path of the file like yours does. Obviously the .1 is because this was a second attempt at installing at d:\signalk and the zipfile is already there.

will do re the venus question in a while, thanks!

V.

PS. all Defender A/V features were off for the attempt. Win10Pro, version 1909, OS built 18363.1316

**Comment by cmotelet** [comment]
Windows is definitely a crazy world ;-)
I have no idea what's wrong !

If you have some time to help me to debug the problem, can you :
- download `https://eternallybored.org/misc/wget/1.20/32/wget.exe` in d:\signalk (change drive letter if you want but directory must exist)
- Open a `cmd.exe` shell
- Run inside: "d:\signalk\wget.exe" −O "d:\signalk\nodejs.zip" "https://nodejs.org/dist/v10.23.0/node-v10.23.0-win-x64.zip"
- Run inside: "d:\signalk\wget.exe" "--output-document=d:\signalk\nodejs.zip" "https://nodejs.org/dist/v10.23.0/node-v10.23.0-win-x64.zip"
- And please give me the screenshot
- If failed, download `https://eternallybored.org/misc/wget/1.20/64/wget.exe` in d:\signalk (replace the previous wget.exe)
- Re run the 2 previous `wget.exe` commands above 
- And give me the screenshot

**Comment by virtuvas** [comment]
am I going to disappoint you if I tell you that I didn't bother doing any downloading, as there was a leftover wget.xe in d:\signalk folder and I just run (no double quotes, nothing!):

`wget -O nodejs.zip https://nodejs.org/dist/v10.23.0/node-v10.23.0-win-x64.zip`

and I now have nodejs.zip fine on d:\signalk
:-)

What's going on???

V.

**Comment by cmotelet** [comment]
Yes but with the double quotes and full path like installer do ?

**Comment by virtuvas** [comment]
doesn't work, either command fails. Check the cmd message in the pic below.
Am I doing something wrong (again!) or is there another issue?

cheers

V.
![wget_test1](https://user-images.githubusercontent.com/17377407/107771778-f5435880-6d43-11eb-9d57-577b6d2d0993.jpg)

**Comment by cmotelet** [comment]
not in `Powershell Windows` but in `cmd Windows`

**Comment by virtuvas** [comment]
oops! sorry...

well happy with the second line with the --output-document= flag all in double quotes.  First line seems to ignore the -O and simply saves the file it downloads as is.
Haven't tried downloading other wget.exes, shall I do that, doubt it's going to make any difference as it seems to be a syntax issue

![wget_test2](https://user-images.githubusercontent.com/17377407/107773315-24f36000-6d46-11eb-9336-d94194c6d68f.jpg)

**Comment by cmotelet** [comment]
Perfect and many thanks.
I'll generate a new release with this fix.

**Comment by virtuvas** [comment]
glad to be of help!
